# Generated by Django 5.0.4 on 2024-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='average_price',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Pending'), ('Filled', 'Filled'), ('PartiallyFilled', 'Partially Field'), ('PartiallyFilledCanceled', 'Partially Filled Cancelled'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='average_entry_price',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='realized_usdt_pnl',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='stop_loss_price',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='take_profit_price',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='unrealized_usdt_pnl',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='value',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
    ]
