# Generated by Django 5.0.4 on 2024-05-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_order_average_price_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='precision',
            field=models.IntegerField(default=8),
        ),
    ]
