# Generated by Django 5.0.4 on 2024-05-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_position_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='side',
            field=models.CharField(blank=True, choices=[('Long', 'Long'), ('Short', 'Short')], max_length=50, null=True),
        ),
    ]
