# Generated by Django 5.0.4 on 2024-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_position_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='break_even_price',
            field=models.DecimalField(decimal_places=16, max_digits=32, null=True),
        ),
    ]
